"""Add supplier and shipment tracking

Revision ID: f25b3ce9e866
Revises: c5d3e4f9b2a4
Create Date: 2026-01-12 15:18:45.323805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25b3ce9e866'
down_revision: Union[str, Sequence[str], None] = 'c5d3e4f9b2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supported_services', sa.JSON(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_configurations_carrier_name'), 'carrier_configurations', ['carrier_name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('preferred_carrier', sa.String(length=100), nullable=True),
    sa.Column('xero_contact_id', sa.String(length=255), nullable=True),
    sa.Column('xero_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_company_name'), 'suppliers', ['company_name'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('delivery_location', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('xero_purchase_order_id', sa.String(length=255), nullable=True),
    sa.Column('xero_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_delivery_location'), 'purchase_orders', ['delivery_location'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('inbound_shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('carrier_service', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('origin_address', sa.Text(), nullable=True),
    sa.Column('destination_location', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('shipped_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_events', sa.JSON(), nullable=True),
    sa.Column('last_tracking_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_shipments_destination_location'), 'inbound_shipments', ['destination_location'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_purchase_order_id'), 'inbound_shipments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_shipment_number'), 'inbound_shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_inbound_shipments_status'), 'inbound_shipments', ['status'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_supplier_id'), 'inbound_shipments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_tracking_number'), 'inbound_shipments', ['tracking_number'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('outbound_shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('carrier_service', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('origin_location', sa.String(length=50), nullable=False),
    sa.Column('destination_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('shipped_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_events', sa.JSON(), nullable=True),
    sa.Column('last_tracking_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_shipments_order_id'), 'outbound_shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_outbound_shipments_origin_location'), 'outbound_shipments', ['origin_location'], unique=False)
    op.create_index(op.f('ix_outbound_shipments_shipment_number'), 'outbound_shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_outbound_shipments_status'), 'outbound_shipments', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_shipments_tracking_number'), 'outbound_shipments', ['tracking_number'], unique=False)
    # COMMENTED OUT: Preserve existing tables that aren't in current models
    # op.drop_index(op.f('ix_shopify_product_mappings_product_id'), table_name='shopify_product_mappings')
    # op.drop_index(op.f('ix_shopify_product_mappings_shopify_product_id'), table_name='shopify_product_mappings')
    # op.drop_index(op.f('ix_shopify_product_mappings_shopify_variant_id'), table_name='shopify_product_mappings')
    # op.drop_table('shopify_product_mappings')
    # op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    # op.drop_index(op.f('ix_service_requests_order_id'), table_name='service_requests')
    # op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    # op.drop_table('service_requests')
    # op.drop_index(op.f('ix_learning_patterns_agent_id'), table_name='learning_patterns')
    # op.drop_index(op.f('ix_learning_patterns_pattern_id'), table_name='learning_patterns')
    # op.drop_index(op.f('ix_learning_patterns_pattern_type'), table_name='learning_patterns')
    # op.drop_table('learning_patterns')
    # op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    # op.drop_index(op.f('ix_payments_xero_payment_id'), table_name='payments')
    # op.drop_table('payments')
    # op.drop_index(op.f('ix_email_conversations_customer_email'), table_name='email_conversations')
    # op.drop_index(op.f('ix_email_conversations_customer_id'), table_name='email_conversations')
    # op.drop_index(op.f('ix_email_conversations_intent'), table_name='email_conversations')
    # op.drop_index(op.f('ix_email_conversations_status'), table_name='email_conversations')
    # op.drop_index(op.f('ix_email_conversations_thread_id'), table_name='email_conversations')
    # op.drop_table('email_conversations')
    # op.drop_index(op.f('ix_email_webhook_logs_email_message_id'), table_name='email_webhook_logs')
    # op.drop_index(op.f('ix_email_webhook_logs_event_type'), table_name='email_webhook_logs')
    # op.drop_index(op.f('ix_email_webpack_logs_sendgrid_message_id'), table_name='email_webhook_logs')
    # op.drop_table('email_webhook_logs')
    # op.drop_index(op.f('ix_shopify_order_mappings_order_id'), table_name='shopify_order_mappings')
    # op.drop_index(op.f('ix_shopify_order_mappings_shopify_order_id'), table_name='shopify_order_mappings')
    # op.drop_table('shopify_order_mappings')
    # op.drop_index(op.f('ix_prompt_variants_agent_id'), table_name='prompt_variants')
    # op.drop_index(op.f('ix_prompt_variants_variant_id'), table_name='prompt_variants')
    # op.drop_table('prompt_variants')
    # op.drop_index(op.f('ix_xero_connections_is_active'), table_name='xero_connections')
    # op.drop_index(op.f('ix_xero_connections_organization_id'), table_name='xero_connections')
    # op.drop_index(op.f('ix_xero_connections_tenant_id'), table_name='xero_connections')
    # op.drop_table('xero_connections')
    # op.drop_index(op.f('ix_shopify_connections_shop_domain'), table_name='shopify_connections')
    # op.drop_table('shopify_connections')
    # op.drop_index(op.f('ix_email_messages_conversation_id'), table_name='email_messages')
    # op.drop_index(op.f('ix_email_messages_direction'), table_name='email_messages')
    # op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    # op.drop_index(op.f('ix_email_messages_sendgrid_message_id'), table_name='email_messages')
    # op.drop_table('email_messages')
    # op.drop_index(op.f('ix_email_templates_category'), table_name='email_templates')
    # op.drop_index(op.f('ix_email_templates_template_key'), table_name='email_templates')
    # op.drop_table('email_templates')
    # op.drop_index(op.f('ix_shopify_webhook_logs_received_at'), table_name='shopify_webhook_logs')
    # op.drop_index(op.f('ix_shopify_webhook_logs_shop_domain'), table_name='shopify_webhook_logs')
    # op.drop_index(op.f('ix_shopify_webhook_logs_topic'), table_name='shopify_webhook_logs')
    # op.drop_table('shopify_webhook_logs')
    # op.drop_index(op.f('ix_learning_insights_agent_id'), table_name='learning_insights')
    # op.drop_index(op.f('ix_learning_insights_insight_id'), table_name='learning_insights')
    # op.drop_index(op.f('ix_learning_insights_insight_type'), table_name='learning_insights')
    # op.drop_index(op.f('ix_learning_insights_priority'), table_name='learning_insights')
    # op.drop_table('learning_insights')

    # COMMENTED OUT: Don't modify agent_executions table
    # op.add_column('agent_executions', sa.Column('context_snapshot', sa.Text(), nullable=True))
    # op.add_column('agent_executions', sa.Column('tokens_used', sa.Integer(), nullable=True))
    # op.add_column('agent_executions', sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    # op.add_column('agent_executions', sa.Column('initiated_by', sa.String(length=50), nullable=False))
    # op.add_column('agent_executions', sa.Column('parent_execution_id', sa.UUID(), nullable=True))
    # op.create_index(op.f('ix_agent_executions_created_at'), 'agent_executions', ['created_at'], unique=False)
    # op.create_index(op.f('ix_agent_executions_parent_execution_id'), 'agent_executions', ['parent_execution_id'], unique=False)

    # COMMENTED OUT: Preserve existing schema, only add new columns
    # op.add_column('ai_generated_content', sa.Column('content_metadata', sa.Text(), nullable=True))
    # op.drop_column('ai_generated_content', 'metadata')
    # op.alter_column('customers', 'contact_name',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('customers', 'email',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('customers', 'phone',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    # op.alter_column('customers', 'postcode',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)
    # op.drop_constraint(op.f('customers_customer_number_key'), 'customers', type_='unique')
    # op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    # op.drop_index(op.f('ix_customers_xero_contact_id'), table_name='customers')
    # op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    # op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    # op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    # op.alter_column('order_items', 'product_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    # op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ADD NEW TRACKING COLUMNS TO ORDERS (KEEP THIS)
    op.add_column('orders', sa.Column('fulfillment_location', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('carrier_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipped_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True))

    # COMMENTED OUT: Don't change existing constraints
    # op.alter_column('orders', 'customer_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('orders', 'subtotal',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False)
    # op.alter_column('orders', 'tax',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False)
    # op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    # op.drop_index(op.f('ix_orders_xero_invoice_id'), table_name='orders')
    # op.drop_index(op.f('ix_orders_xero_sync_status'), table_name='orders')
    # op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    # op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    # op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_fulfillment_location'), 'orders', ['fulfillment_location'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=False)

    # COMMENTED OUT: Don't modify existing foreign keys and organizations
    # op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    # op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # op.add_column('organizations', sa.Column('slug', sa.String(length=100), nullable=False))
    # op.drop_constraint(op.f('organizations_subdomain_key'), 'organizations', type_='unique')
    # op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    # op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # op.drop_column('organizations', 'subdomain')
    # op.alter_column('products', 'category',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('HEAVY_MACHINERY', 'HAND_TOOLS', 'POWER_TOOLS', 'SAFETY_EQUIPMENT', 'BUILDING_MATERIALS', 'ELECTRICAL', 'PLUMBING', 'ACCESSORIES', name='product_category'),
    #            existing_nullable=False)
    # op.alter_column('products', 'cost',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False)
    # op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    # op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    # op.drop_index(op.f('ix_products_sku'), table_name='products')
    # op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # op.alter_column('quote_items', 'product_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.create_index(op.f('ix_quote_items_product_id'), 'quote_items', ['product_id'], unique=False)
    # op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    # op.drop_constraint(op.f('quote_items_product_id_fkey'), 'quote_items', type_='foreignkey')
    # op.create_foreign_key(None, 'quote_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # op.alter_column('quotes', 'customer_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('quotes', 'subtotal',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False)
    # op.alter_column('quotes', 'tax',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            nullable=False)
    # op.drop_index(op.f('ix_quotes_organization_id'), table_name='quotes')
    # op.drop_constraint(op.f('quotes_quote_number_key'), 'quotes', type_='unique')
    # op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    # op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    # op.create_index(op.f('ix_quotes_quote_date'), 'quotes', ['quote_date'], unique=False)
    # op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    # op.drop_constraint(op.f('quotes_customer_id_fkey'), 'quotes', type_='foreignkey')
    # op.create_foreign_key(None, 'quotes', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    # op.drop_column('users', 'organization_id')
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'employee'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_foreign_key(op.f('quotes_customer_id_fkey'), 'quotes', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_date'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=False)
    op.create_unique_constraint(op.f('quotes_quote_number_key'), 'quotes', ['quote_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_quotes_organization_id'), 'quotes', ['organization_id'], unique=False)
    op.alter_column('quotes', 'tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('quotes', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('quotes', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'quote_items', type_='foreignkey')
    op.create_foreign_key(op.f('quote_items_product_id_fkey'), 'quote_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_index(op.f('ix_quote_items_product_id'), table_name='quote_items')
    op.alter_column('quote_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.alter_column('products', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.Enum('HEAVY_MACHINERY', 'HAND_TOOLS', 'POWER_TOOLS', 'SAFETY_EQUIPMENT', 'BUILDING_MATERIALS', 'ELECTRICAL', 'PLUMBING', 'ACCESSORIES', name='product_category'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('organizations', sa.Column('subdomain', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_unique_constraint(op.f('organizations_subdomain_key'), 'organizations', ['subdomain'], postgresql_nulls_not_distinct=False)
    op.drop_column('organizations', 'slug')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_fulfillment_location'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orders_xero_sync_status'), 'orders', ['xero_sync_status'], unique=False)
    op.create_index(op.f('ix_orders_xero_invoice_id'), 'orders', ['xero_invoice_id'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.alter_column('orders', 'tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'shipped_date')
    op.drop_column('orders', 'carrier_name')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'fulfillment_location')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=False)
    op.create_index(op.f('ix_customers_xero_contact_id'), 'customers', ['xero_contact_id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('customers_customer_number_key'), 'customers', ['customer_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'postcode',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('ai_generated_content', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ai_generated_content', 'content_metadata')
    op.drop_index(op.f('ix_agent_executions_parent_execution_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_created_at'), table_name='agent_executions')
    op.drop_column('agent_executions', 'parent_execution_id')
    op.drop_column('agent_executions', 'initiated_by')
    op.drop_column('agent_executions', 'estimated_cost_usd')
    op.drop_column('agent_executions', 'tokens_used')
    op.drop_column('agent_executions', 'context_snapshot')
    op.create_table('learning_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('insight_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommended_action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expected_improvement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('supporting_patterns', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_implemented', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('implemented_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_insights_pkey')),
    sa.UniqueConstraint('insight_id', name=op.f('learning_insights_insight_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_learning_insights_priority'), 'learning_insights', ['priority'], unique=False)
    op.create_index(op.f('ix_learning_insights_insight_type'), 'learning_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_learning_insights_insight_id'), 'learning_insights', ['insight_id'], unique=False)
    op.create_index(op.f('ix_learning_insights_agent_id'), 'learning_insights', ['agent_id'], unique=False)
    op.create_table('shopify_webhook_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shopify_webhook_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shop_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_webhook_logs_pkey'))
    )
    op.create_index(op.f('ix_shopify_webhook_logs_topic'), 'shopify_webhook_logs', ['topic'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_logs_shop_domain'), 'shopify_webhook_logs', ['shop_domain'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_logs_received_at'), 'shopify_webhook_logs', ['received_at'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject_template', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body_text_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body_html_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sendgrid_template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('required_variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_templates_pkey'))
    )
    op.create_index(op.f('ix_email_templates_template_key'), 'email_templates', ['template_key'], unique=True)
    op.create_index(op.f('ix_email_templates_category'), 'email_templates', ['category'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('from_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('from_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('to_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cc_emails', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bcc_emails', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('was_ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sendgrid_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sendgrid_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_messages_pkey'))
    )
    op.create_index(op.f('ix_email_messages_sendgrid_message_id'), 'email_messages', ['sendgrid_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_email_messages_direction'), 'email_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_email_messages_conversation_id'), 'email_messages', ['conversation_id'], unique=False)
    op.create_table('shopify_connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shop_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('shop_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('api_secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('webhook_secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_order_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_inventory_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_product_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sync_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_connections_pkey'))
    )
    op.create_index(op.f('ix_shopify_connections_shop_domain'), 'shopify_connections', ['shop_domain'], unique=True)
    op.create_table('xero_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tenant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('xero_connections_pkey'))
    )
    op.create_index(op.f('ix_xero_connections_tenant_id'), 'xero_connections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_xero_connections_organization_id'), 'xero_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_xero_connections_is_active'), 'xero_connections', ['is_active'], unique=False)
    op.create_table('prompt_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('executions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failure_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avg_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_used', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_variants_pkey')),
    sa.UniqueConstraint('variant_id', name=op.f('prompt_variants_variant_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_prompt_variants_variant_id'), 'prompt_variants', ['variant_id'], unique=False)
    op.create_index(op.f('ix_prompt_variants_agent_id'), 'prompt_variants', ['agent_id'], unique=False)
    op.create_table('shopify_order_mappings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shopify_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shopify_order_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shopify_order_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('import_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('financial_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fulfillment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shopify_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_order_mappings_pkey'))
    )
    op.create_index(op.f('ix_shopify_order_mappings_shopify_order_id'), 'shopify_order_mappings', ['shopify_order_id'], unique=True)
    op.create_index(op.f('ix_shopify_order_mappings_order_id'), 'shopify_order_mappings', ['order_id'], unique=True)
    op.create_table('email_webhook_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sendgrid_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_webhook_logs_pkey'))
    )
    op.create_index(op.f('ix_email_webhook_logs_sendgrid_message_id'), 'email_webhook_logs', ['sendgrid_message_id'], unique=False)
    op.create_index(op.f('ix_email_webhook_logs_event_type'), 'email_webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_webhook_logs_email_message_id'), 'email_webhook_logs', ['email_message_id'], unique=False)
    op.create_table('email_conversations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('related_order_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('related_product_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('related_quote_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_conversations_pkey'))
    )
    op.create_index(op.f('ix_email_conversations_thread_id'), 'email_conversations', ['thread_id'], unique=True)
    op.create_index(op.f('ix_email_conversations_status'), 'email_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_email_conversations_intent'), 'email_conversations', ['intent'], unique=False)
    op.create_index(op.f('ix_email_conversations_customer_id'), 'email_conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_email_conversations_customer_email'), 'email_conversations', ['customer_email'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('xero_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), server_default=sa.text("'other'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('payments_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('xero_payment_id', name=op.f('payments_xero_payment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_payments_xero_payment_id'), 'payments', ['xero_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('learning_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('pattern_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('task_category', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('observed_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('outcomes', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('pattern_metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('first_observed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_observed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_patterns_pkey')),
    sa.UniqueConstraint('pattern_id', name=op.f('learning_patterns_pattern_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_learning_patterns_pattern_type'), 'learning_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_learning_patterns_pattern_id'), 'learning_patterns', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_learning_patterns_agent_id'), 'learning_patterns', ['agent_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('request_type', postgresql.ENUM('repair', 'maintenance', 'installation', name='request_type_enum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('submitted', 'quoted', 'approved', 'in_progress', 'completed', 'cancelled', name='service_status_enum'), autoincrement=False, nullable=False),
    sa.Column('equipment_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issue_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assigned_technician', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('quote_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('approved_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('approved_amount IS NULL OR approved_amount >= 0::numeric', name=op.f('ck_approved_amount_non_negative')),
    sa.CheckConstraint('quote_amount IS NULL OR quote_amount >= 0::numeric', name=op.f('ck_quote_amount_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('service_requests_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('service_requests_order_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('service_requests_pkey'))
    )
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_order_id'), 'service_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_table('shopify_product_mappings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shopify_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shopify_variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shopify_inventory_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shopify_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_product_mappings_pkey'))
    )
    op.create_index(op.f('ix_shopify_product_mappings_shopify_variant_id'), 'shopify_product_mappings', ['shopify_variant_id'], unique=False)
    op.create_index(op.f('ix_shopify_product_mappings_shopify_product_id'), 'shopify_product_mappings', ['shopify_product_id'], unique=False)
    op.create_index(op.f('ix_shopify_product_mappings_product_id'), 'shopify_product_mappings', ['product_id'], unique=False)
    op.drop_index(op.f('ix_outbound_shipments_tracking_number'), table_name='outbound_shipments')
    op.drop_index(op.f('ix_outbound_shipments_status'), table_name='outbound_shipments')
    op.drop_index(op.f('ix_outbound_shipments_shipment_number'), table_name='outbound_shipments')
    op.drop_index(op.f('ix_outbound_shipments_origin_location'), table_name='outbound_shipments')
    op.drop_index(op.f('ix_outbound_shipments_order_id'), table_name='outbound_shipments')
    op.drop_table('outbound_shipments')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_inbound_shipments_tracking_number'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_supplier_id'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_status'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_shipment_number'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_purchase_order_id'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_destination_location'), table_name='inbound_shipments')
    op.drop_table('inbound_shipments')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_delivery_location'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_carrier_configurations_carrier_name'), table_name='carrier_configurations')
    op.drop_table('carrier_configurations')
    # ### end Alembic commands ###
