ALTER TABLE ONLY public.agent_executions
ALTER TABLE ONLY public.agent_runs
ALTER TABLE ONLY public.ai_generated_content
ALTER TABLE ONLY public.alembic_version
ALTER TABLE ONLY public.api_usage
ALTER TABLE ONLY public.availability_slots
ALTER TABLE ONLY public.background_jobs
ALTER TABLE ONLY public.backorders
ALTER TABLE ONLY public.carrier_configurations
ALTER TABLE ONLY public.container_items
ALTER TABLE ONLY public.containers
ALTER TABLE ONLY public.contractors
ALTER TABLE ONLY public.conversation_history
ALTER TABLE ONLY public.customers
ALTER TABLE ONLY public.customers
ALTER TABLE ONLY public.documents
ALTER TABLE ONLY public.inbound_shipments
ALTER TABLE ONLY public.learning_insights
ALTER TABLE ONLY public.learning_insights
ALTER TABLE ONLY public.learning_patterns
ALTER TABLE ONLY public.learning_patterns
ALTER TABLE ONLY public.order_activity
ALTER TABLE ONLY public.order_items
ALTER TABLE ONLY public.orders
ALTER TABLE ONLY public.orders
ALTER TABLE ONLY public.organizations
ALTER TABLE ONLY public.organizations
ALTER TABLE ONLY public.outbound_shipments
ALTER TABLE ONLY public.payments
ALTER TABLE ONLY public.payments
ALTER TABLE ONLY public.prds
ALTER TABLE ONLY public.product_stock_by_location
ALTER TABLE ONLY public.products
ALTER TABLE ONLY public.products
ALTER TABLE ONLY public.prompt_variants
ALTER TABLE ONLY public.prompt_variants
ALTER TABLE ONLY public.purchase_order_items
ALTER TABLE ONLY public.purchase_orders
ALTER TABLE ONLY public.quote_items
ALTER TABLE ONLY public.quotes
ALTER TABLE ONLY public.quotes
ALTER TABLE ONLY public.stock_adjustments
ALTER TABLE ONLY public.stock_reservations
ALTER TABLE ONLY public.stock_transfers
ALTER TABLE ONLY public.suppliers
ALTER TABLE ONLY public.product_stock_by_location
ALTER TABLE ONLY public.users
ALTER TABLE ONLY public.users
ALTER TABLE ONLY public.xero_connections
ALTER TABLE ONLY public.agent_runs
ALTER TABLE ONLY public.api_usage
ALTER TABLE ONLY public.availability_slots
ALTER TABLE ONLY public.backorders
ALTER TABLE ONLY public.backorders
ALTER TABLE ONLY public.backorders
ALTER TABLE ONLY public.backorders
ALTER TABLE ONLY public.backorders
ALTER TABLE ONLY public.container_items
ALTER TABLE ONLY public.container_items
ALTER TABLE ONLY public.containers
ALTER TABLE ONLY public.containers
ALTER TABLE ONLY public.containers
ALTER TABLE ONLY public.contractors
ALTER TABLE ONLY public.customers
ALTER TABLE ONLY public.documents
ALTER TABLE ONLY public.inbound_shipments
ALTER TABLE ONLY public.inbound_shipments
ALTER TABLE ONLY public.order_activity
ALTER TABLE ONLY public.order_items
ALTER TABLE ONLY public.order_items
ALTER TABLE ONLY public.orders
ALTER TABLE ONLY public.orders
ALTER TABLE ONLY public.outbound_shipments
ALTER TABLE ONLY public.payments
ALTER TABLE ONLY public.prds
ALTER TABLE ONLY public.prds
ALTER TABLE ONLY public.product_stock_by_location
ALTER TABLE ONLY public.products
ALTER TABLE ONLY public.purchase_order_items
ALTER TABLE ONLY public.purchase_order_items
ALTER TABLE ONLY public.purchase_orders
ALTER TABLE ONLY public.purchase_orders
ALTER TABLE ONLY public.quote_items
ALTER TABLE ONLY public.quote_items
ALTER TABLE ONLY public.quotes
ALTER TABLE ONLY public.quotes
ALTER TABLE ONLY public.stock_adjustments
ALTER TABLE ONLY public.stock_reservations
ALTER TABLE ONLY public.stock_reservations
ALTER TABLE ONLY public.stock_transfers
ALTER TABLE ONLY public.users
