#!/usr/bin/env python3
"""Catalog Doctor — AST-based regenerator for docs/catalogs/.

Reads the live codebase and rewrites:
  docs/catalogs/ROUTES.md  — FastAPI endpoints (method + path + file)
  docs/catalogs/PAGES.md   — Next.js App Router pages (route + file)
  docs/catalogs/MODELS.md  — SQLAlchemy models (__tablename__ + class + file)

Usage:
  python scripts/catalog_doctor.py          # regenerate all three catalogs
  python scripts/catalog_doctor.py --check  # exit 1 if catalogs are stale

Wire to Turbo:
  pnpm docs:verify   (see package.json / turbo.json)
"""

from __future__ import annotations

import ast
import argparse
import sys
from datetime import date
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_ROUTES = REPO_ROOT / "apps" / "backend" / "src" / "api" / "routes"
FRONTEND_APP = REPO_ROOT / "apps" / "web" / "app"
BACKEND_DB = REPO_ROOT / "apps" / "backend" / "src" / "db"
CATALOGS = REPO_ROOT / "docs" / "catalogs"

TODAY = date.today().isoformat()

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options", "trace"}


# ─────────────────────────────────────────────────────────────────────────────
# FastAPI route extraction
# ─────────────────────────────────────────────────────────────────────────────

def _extract_routes(py_file: Path) -> list[dict]:
    """Return list of {method, path, file} from a FastAPI router file."""
    try:
        tree = ast.parse(py_file.read_text(encoding="utf-8"))
    except SyntaxError:
        return []

    routes: list[dict] = []
    rel = py_file.relative_to(REPO_ROOT).as_posix()

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        for decorator in node.decorator_list:
            method, path = _parse_route_decorator(decorator)
            if method:
                routes.append({"method": method.upper(), "path": path, "file": rel, "func": node.name})

    return routes


def _parse_route_decorator(decorator) -> tuple[str | None, str]:
    """Return (method, path) from a @router.{method}("path") decorator, else (None, "")."""
    if not isinstance(decorator, ast.Call):
        return None, ""

    func = decorator.func
    if not isinstance(func, ast.Attribute):
        return None, ""

    method = func.attr.lower()
    if method not in HTTP_METHODS:
        return None, ""

    path = ""
    if decorator.args:
        first = decorator.args[0]
        if isinstance(first, ast.Constant):
            path = str(first.value)

    return method, path


def build_routes_md() -> str:
    route_files = sorted(BACKEND_ROUTES.rglob("*.py"))
    all_routes: list[dict] = []
    for f in route_files:
        if f.name.startswith("__"):
            continue
        all_routes.extend(_extract_routes(f))

    lines = [
        "# Routes Catalog — CCW ERP/CRM",
        "",
        f"_Auto-generated by `scripts/catalog_doctor.py` on {TODAY}_",
        f"_Total endpoints: {len(all_routes)}_",
        f"_Source: `apps/backend/src/api/routes/`_",
        "",
        "---",
        "",
        "| # | Method | Path | File |",
        "|---|--------|------|------|",
    ]
    for i, r in enumerate(all_routes, 1):
        lines.append(f"| {i} | `{r['method']}` | `{r['path']}` | `{r['file']}` |")

    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# Next.js page extraction
# ─────────────────────────────────────────────────────────────────────────────

def _file_to_route(page_file: Path) -> str:
    """Convert apps/web/app/(dashboard)/orders/page.tsx → /orders"""
    rel = page_file.relative_to(FRONTEND_APP)
    parts = rel.parts[:-1]  # drop page.tsx
    clean: list[str] = []
    for p in parts:
        if p.startswith("(") and p.endswith(")"):
            continue  # skip Next.js route groups like (dashboard)
        clean.append(p)
    return "/" + "/".join(clean) if clean else "/"


def build_pages_md() -> str:
    page_files = sorted(FRONTEND_APP.rglob("page.tsx"))
    pages: list[dict] = []
    for f in page_files:
        route = _file_to_route(f)
        rel = f.relative_to(REPO_ROOT).as_posix()
        pages.append({"route": route, "file": rel})

    lines = [
        "# Pages Catalog — CCW ERP/CRM Frontend",
        "",
        f"_Auto-generated by `scripts/catalog_doctor.py` on {TODAY}_",
        f"_Total pages: {len(pages)}_",
        f"_Source: `apps/web/app/`_",
        "",
        "---",
        "",
        "| # | Route | File |",
        "|---|-------|------|",
    ]
    for i, p in enumerate(pages, 1):
        lines.append(f"| {i} | `{p['route']}` | `{p['file']}` |")

    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# SQLAlchemy model extraction
# ─────────────────────────────────────────────────────────────────────────────

def _extract_models(py_file: Path) -> list[dict]:
    """Return list of {class_name, table_name, file} from a db models file."""
    try:
        tree = ast.parse(py_file.read_text(encoding="utf-8"))
    except SyntaxError:
        return []

    rel = py_file.relative_to(REPO_ROOT).as_posix()
    models: list[dict] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        table_name = _find_tablename(node)
        if table_name:
            locked = "demo_models.py" in rel
            models.append({
                "class": node.name,
                "table": table_name,
                "file": rel,
                "locked": locked,
            })

    return models


def _find_tablename(class_node: ast.ClassDef) -> str | None:
    """Return __tablename__ string value from a class body, or None."""
    for stmt in class_node.body:
        if not isinstance(stmt, ast.Assign):
            continue
        for target in stmt.targets:
            if isinstance(target, ast.Name) and target.id == "__tablename__":
                if isinstance(stmt.value, ast.Constant):
                    return str(stmt.value.value)
    return None


def build_models_md() -> str:
    db_files = sorted(BACKEND_DB.glob("*.py"))
    all_models: list[dict] = []
    for f in db_files:
        if f.name.startswith("__"):
            continue
        all_models.extend(_extract_models(f))

    lines = [
        "# Models Catalog — CCW ERP/CRM Database",
        "",
        f"_Auto-generated by `scripts/catalog_doctor.py` on {TODAY}_",
        f"_Total models: {len(all_models)}_",
        f"_Source: `apps/backend/src/db/`_",
        "_WARNING: `demo_models.py` is LOCKED — do not modify without explicit approval_",
        "",
        "---",
        "",
        "| # | Class | Table | File | Locked |",
        "|---|-------|-------|------|--------|",
    ]
    for i, m in enumerate(all_models, 1):
        locked_marker = "🔒" if m["locked"] else ""
        lines.append(f"| {i} | `{m['class']}` | `{m['table']}` | `{m['file']}` | {locked_marker} |")

    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/catalogs/ from source.")
    parser.add_argument("--check", action="store_true", help="Exit 1 if catalogs are stale (no writes)")
    args = parser.parse_args()

    CATALOGS.mkdir(parents=True, exist_ok=True)

    targets = [
        (CATALOGS / "ROUTES.md", build_routes_md),
        (CATALOGS / "PAGES.md", build_pages_md),
        (CATALOGS / "MODELS.md", build_models_md),
    ]

    stale = False
    for catalog_path, builder in targets:
        new_content = builder()
        if args.check:
            existing = catalog_path.read_text(encoding="utf-8") if catalog_path.exists() else ""
            if existing != new_content:
                print(f"STALE: {catalog_path.relative_to(REPO_ROOT)}")
                stale = True
            else:
                print(f"OK:    {catalog_path.relative_to(REPO_ROOT)}")
        else:
            catalog_path.write_text(new_content, encoding="utf-8")
            print(f"Wrote: {catalog_path.relative_to(REPO_ROOT)}")

    if args.check and stale:
        print("\nRun `pnpm docs:verify` to regenerate stale catalogs.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
