-- Insert 100 CCW Equipment Products (keeping existing products)
-- Note: Will skip if SKU already exists due to unique constraint
-- Heavy Machinery (15 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-HM-001', 'Excavator 20T Hitachi ZX200', 'Professional grade excavator 20t hitachi zx200 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 185000, 145000, 2, 'Bay A-05', true),
('CCW-HM-002', 'Skid Steer Loader Bobcat S570', 'Professional grade skid steer loader bobcat s570 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 65000, 52000, 3, 'Bay B-12', true),
('CCW-HM-003', 'Wheel Loader CAT 950M', 'Professional grade wheel loader cat 950m for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 275000, 220000, 1, 'Bay C-08', true),
('CCW-HM-004', 'Bulldozer Komatsu D65PX', 'Professional grade bulldozer komatsu d65px for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 385000, 310000, 1, 'Bay D-15', true),
('CCW-HM-005', 'Backhoe Loader JCB 3CX', 'Professional grade backhoe loader jcb 3cx for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 95000, 76000, 2, 'Bay A-18', true),
('CCW-HM-006', 'Motor Grader CAT 140M', 'Professional grade motor grader cat 140m for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 425000, 340000, 1, 'Bay B-03', true),
('CCW-HM-007', 'Telehandler JLG 3614', 'Professional grade telehandler jlg 3614 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 85000, 68000, 4, 'Bay C-11', true),
('CCW-HM-008', 'Forklift Toyota 8FG25', 'Professional grade forklift toyota 8fg25 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 35000, 28000, 5, 'Bay D-07', true),
('CCW-HM-009', 'Compactor Bomag BW211D', 'Professional grade compactor bomag bw211d for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 125000, 100000, 2, 'Bay A-14', true),
('CCW-HM-010', 'Trencher Ditch Witch RT80', 'Professional grade trencher ditch witch rt80 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 95000, 76000, 2, 'Bay B-19', true),
('CCW-HM-011', 'Mini Excavator Kubota KX040', 'Professional grade mini excavator kubota kx040 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 55000, 44000, 6, 'Bay C-06', true),
('CCW-HM-012', 'Track Loader CAT 963K', 'Professional grade track loader cat 963k for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 165000, 132000, 2, 'Bay D-10', true),
('CCW-HM-013', 'Scissor Lift Genie GS3246', 'Professional grade scissor lift genie gs3246 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 28000, 22400, 8, 'Bay A-02', true),
('CCW-HM-014', 'Boom Lift JLG 600S', 'Professional grade boom lift jlg 600s for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 75000, 60000, 3, 'Bay B-16', true),
('CCW-HM-015', 'Pallet Jack Manual 2500kg', 'Professional grade pallet jack manual 2500kg for commercial and industrial use. High quality equipment from trusted manufacturers.', 'heavy_machinery', 850, 680, 25, 'Bay C-13', true);

-- Power Tools (20 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-PT-001', 'Makita Cordless Drill Driver 18V', 'Professional grade makita cordless drill driver 18v for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 285, 228, 45, 'Bay A-09', true),
('CCW-PT-002', 'DeWalt Circular Saw 7-1/4in', 'Professional grade dewalt circular saw 7-1/4in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 195, 156, 38, 'Bay B-05', true),
('CCW-PT-003', 'Bosch Rotary Hammer SDS-Plus', 'Professional grade bosch rotary hammer sds-plus for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 425, 340, 22, 'Bay C-17', true),
('CCW-PT-004', 'Milwaukee Angle Grinder 4-1/2in', 'Professional grade milwaukee angle grinder 4-1/2in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 165, 132, 52, 'Bay D-04', true),
('CCW-PT-005', 'Hilti Impact Wrench 18V', 'Professional grade hilti impact wrench 18v for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 495, 396, 18, 'Bay A-11', true),
('CCW-PT-006', 'Ryobi Reciprocating Saw 18V', 'Professional grade ryobi reciprocating saw 18v for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 155, 124, 35, 'Bay B-08', true),
('CCW-PT-007', 'Festool Track Saw TS 55', 'Professional grade festool track saw ts 55 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 685, 548, 12, 'Bay C-14', true),
('CCW-PT-008', 'Makita Jigsaw 18V Cordless', 'Professional grade makita jigsaw 18v cordless for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 225, 180, 28, 'Bay D-01', true),
('CCW-PT-009', 'DeWalt Nail Gun Framing 18V', 'Professional grade dewalt nail gun framing 18v for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 545, 436, 15, 'Bay A-06', true),
('CCW-PT-010', 'Bosch Router 1/4in Cordless', 'Professional grade bosch router 1/4in cordless for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 295, 236, 24, 'Bay B-13', true),
('CCW-PT-011', 'Milwaukee Multi-Tool Oscillating', 'Professional grade milwaukee multi-tool oscillating for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 245, 196, 32, 'Bay C-09', true),
('CCW-PT-012', 'Makita Belt Sander 3x21in', 'Professional grade makita belt sander 3x21in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 185, 148, 20, 'Bay D-16', true),
('CCW-PT-013', 'DeWalt Mitre Saw 12in Sliding', 'Professional grade dewalt mitre saw 12in sliding for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 625, 500, 14, 'Bay A-03', true),
('CCW-PT-014', 'Bosch Planer 82mm Electric', 'Professional grade bosch planer 82mm electric for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 265, 212, 18, 'Bay B-10', true),
('CCW-PT-015', 'Hitachi Brad Nailer 18GA', 'Professional grade hitachi brad nailer 18ga for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 385, 308, 16, 'Bay C-07', true),
('CCW-PT-016', 'Ryobi Orbital Sander 5in', 'Professional grade ryobi orbital sander 5in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 125, 100, 42, 'Bay D-12', true),
('CCW-PT-017', 'Milwaukee Heat Gun Variable Temp', 'Professional grade milwaukee heat gun variable temp for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 145, 116, 28, 'Bay A-15', true),
('CCW-PT-018', 'Makita Vacuum Extractor 10L', 'Professional grade makita vacuum extractor 10l for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 385, 308, 12, 'Bay B-02', true),
('CCW-PT-019', 'DeWalt Work Light LED 20V', 'Professional grade dewalt work light led 20v for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 95, 76, 65, 'Bay C-18', true),
('CCW-PT-020', 'Bosch Laser Level Self-Leveling', 'Professional grade bosch laser level self-leveling for commercial and industrial use. High quality equipment from trusted manufacturers.', 'power_tools', 295, 236, 22, 'Bay D-09', true);

-- Hand Tools (15 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-HT-001', 'Stanley Hammer Claw 16oz', 'Professional grade stanley hammer claw 16oz for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 35, 28, 125, 'Bay A-08', true),
('CCW-HT-002', 'Bahco Adjustable Wrench Set 3pc', 'Professional grade bahco adjustable wrench set 3pc for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 85, 68, 78, 'Bay B-14', true),
('CCW-HT-003', 'Irwin Pliers Set 5pc', 'Professional grade irwin pliers set 5pc for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 65, 52, 92, 'Bay C-05', true),
('CCW-HT-004', 'Stanley Screwdriver Set 10pc', 'Professional grade stanley screwdriver set 10pc for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 45, 36, 105, 'Bay D-11', true),
('CCW-HT-005', 'Crescent Socket Set 1/2in 42pc', 'Professional grade crescent socket set 1/2in 42pc for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 195, 156, 45, 'Bay A-17', true),
('CCW-HT-006', 'Stanley Tape Measure 8m Professional', 'Professional grade stanley tape measure 8m professional for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 28, 22, 150, 'Bay B-06', true),
('CCW-HT-007', 'Irwin Quick-Grip Clamps Set 4pc', 'Professional grade irwin quick-grip clamps set 4pc for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 75, 60, 62, 'Bay C-12', true),
('CCW-HT-008', 'Stanley Utility Knife Retractable', 'Professional grade stanley utility knife retractable for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 18, 14, 200, 'Bay D-18', true),
('CCW-HT-009', 'Bahco Hacksaw Adjustable Frame', 'Professional grade bahco hacksaw adjustable frame for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 42, 34, 88, 'Bay A-04', true),
('CCW-HT-010', 'Stanley Level Spirit 600mm', 'Professional grade stanley level spirit 600mm for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 55, 44, 72, 'Bay B-11', true),
('CCW-HT-011', 'Irwin Chisel Set 6pc Wood', 'Professional grade irwin chisel set 6pc wood for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 95, 76, 48, 'Bay C-16', true),
('CCW-HT-012', 'Stanley Toolbox Pro 24in', 'Professional grade stanley toolbox pro 24in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 125, 100, 35, 'Bay D-03', true),
('CCW-HT-013', 'Bahco File Set Assorted 5pc', 'Professional grade bahco file set assorted 5pc for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 58, 46, 55, 'Bay A-10', true),
('CCW-HT-014', 'Irwin Vise-Grip Locking Pliers 10in', 'Professional grade irwin vise-grip locking pliers 10in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 48, 38, 82, 'Bay B-17', true),
('CCW-HT-015', 'Stanley Combination Square 12in', 'Professional grade stanley combination square 12in for commercial and industrial use. High quality equipment from trusted manufacturers.', 'hand_tools', 65, 52, 45, 'Bay C-04', true);

-- Safety Equipment (15 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-SE-001', 'Hard Hat Safety Helmet Class E', 'Professional grade hard hat safety helmet class e for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 28, 22, 250, 'Bay D-14', true),
('CCW-SE-002', 'Safety Glasses Clear Lens ANSI Z87', 'Professional grade safety glasses clear lens ansi z87 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 12, 10, 450, 'Bay A-01', true),
('CCW-SE-003', 'Work Gloves Leather Palm Size L', 'Professional grade work gloves leather palm size l for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 18, 14, 320, 'Bay B-07', true),
('CCW-SE-004', 'Hi-Vis Vest Class 2 Orange', 'Professional grade hi-vis vest class 2 orange for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 22, 18, 280, 'Bay C-13', true),
('CCW-SE-005', 'Safety Boots Steel Toe Size 10', 'Professional grade safety boots steel toe size 10 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 125, 100, 85, 'Bay D-19', true),
('CCW-SE-006', 'Ear Muffs Noise Reduction 33dB', 'Professional grade ear muffs noise reduction 33db for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 35, 28, 165, 'Bay A-12', true),
('CCW-SE-007', 'Respirator Half Face P100 Filter', 'Professional grade respirator half face p100 filter for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 65, 52, 95, 'Bay B-18', true),
('CCW-SE-008', 'Fall Protection Harness Full Body', 'Professional grade fall protection harness full body for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 185, 148, 42, 'Bay C-10', true),
('CCW-SE-009', 'First Aid Kit Workplace 50-Person', 'Professional grade first aid kit workplace 50-person for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 95, 76, 55, 'Bay D-06', true),
('CCW-SE-010', 'Fire Extinguisher ABC 10lb', 'Professional grade fire extinguisher abc 10lb for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 75, 60, 68, 'Bay A-16', true),
('CCW-SE-011', 'Safety Goggles Anti-Fog Sealed', 'Professional grade safety goggles anti-fog sealed for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 25, 20, 185, 'Bay B-09', true),
('CCW-SE-012', 'Face Shield Clear Polycarbonate', 'Professional grade face shield clear polycarbonate for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 32, 26, 125, 'Bay C-15', true),
('CCW-SE-013', 'Knee Pads Professional Foam', 'Professional grade knee pads professional foam for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 42, 34, 95, 'Bay D-02', true),
('CCW-SE-014', 'Reflective Tape 2in x 30ft Roll', 'Professional grade reflective tape 2in x 30ft roll for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 18, 14, 220, 'Bay A-19', true),
('CCW-SE-015', 'Safety Cones 28in Traffic Orange 6pk', 'Professional grade safety cones 28in traffic orange 6pk for commercial and industrial use. High quality equipment from trusted manufacturers.', 'safety_equipment', 85, 68, 75, 'Bay B-04', true);

-- Building Materials (15 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-BM-001', 'Plywood Sheet 4x8ft 18mm Marine', 'Professional grade plywood sheet 4x8ft 18mm marine for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 95, 76, 125, 'Bay C-19', true),
('CCW-BM-002', 'Timber Pine 90x45mm 5.4m Treated', 'Professional grade timber pine 90x45mm 5.4m treated for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 28, 22, 450, 'Bay D-08', true),
('CCW-BM-003', 'Cement Bag 20kg General Purpose', 'Professional grade cement bag 20kg general purpose for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 12, 10, 850, 'Bay A-13', true),
('CCW-BM-004', 'Gyprock Plasterboard 2400x1200x13mm', 'Professional grade gyprock plasterboard 2400x1200x13mm for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 18, 14, 380, 'Bay B-20', true),
('CCW-BM-005', 'Insulation Batts R2.5 430mm 8pk', 'Professional grade insulation batts r2.5 430mm 8pk for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 85, 68, 95, 'Bay C-02', true),
('CCW-BM-006', 'Roofing Iron Colorbond 0.42mm 6m', 'Professional grade roofing iron colorbond 0.42mm 6m for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 125, 100, 165, 'Bay D-17', true),
('CCW-BM-007', 'Bricks Red Common 230x110x76mm Pallet', 'Professional grade bricks red common 230x110x76mm pallet for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 850, 680, 25, 'Bay A-07', true),
('CCW-BM-008', 'Concrete Blocks 200mm Standard Pallet', 'Professional grade concrete blocks 200mm standard pallet for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 425, 340, 32, 'Bay B-15', true),
('CCW-BM-009', 'Timber Hardwood 140x19mm Decking 5.4m', 'Professional grade timber hardwood 140x19mm decking 5.4m for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 65, 52, 185, 'Bay C-01', true),
('CCW-BM-010', 'Steel RHS 50x50x3mm 6m Galvanised', 'Professional grade steel rhs 50x50x3mm 6m galvanised for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 95, 76, 78, 'Bay D-13', true),
('CCW-BM-011', 'Sarking Foil Insulation 60m2 Roll', 'Professional grade sarking foil insulation 60m2 roll for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 145, 116, 42, 'Bay A-20', true),
('CCW-BM-012', 'Mesh Reinforcement SL92 6x2.4m Sheet', 'Professional grade mesh reinforcement sl92 6x2.4m sheet for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 75, 60, 95, 'Bay B-01', true),
('CCW-BM-013', 'Gravel 20mm Blue Metal Tonne Bag', 'Professional grade gravel 20mm blue metal tonne bag for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 125, 100, 55, 'Bay C-08', true),
('CCW-BM-014', 'Sand River Washed Tonne Bag', 'Professional grade sand river washed tonne bag for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 85, 68, 68, 'Bay D-05', true),
('CCW-BM-015', 'Screws Deck Stainless 10g x 75mm 1kg', 'Professional grade screws deck stainless 10g x 75mm 1kg for commercial and industrial use. High quality equipment from trusted manufacturers.', 'building_materials', 45, 36, 125, 'Bay A-14', true);

-- Electrical (10 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-EL-001', 'Cable Extension Lead 20m Heavy Duty', 'Professional grade cable extension lead 20m heavy duty for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 85, 68, 65, 'Bay B-12', true),
('CCW-EL-002', 'LED Work Light 50W Portable', 'Professional grade led work light 50w portable for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 125, 100, 48, 'Bay C-18', true),
('CCW-EL-003', 'Power Board 6 Outlet Surge Protected', 'Professional grade power board 6 outlet surge protected for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 45, 36, 125, 'Bay D-10', true),
('CCW-EL-004', 'Cable Ties Black 200mm 100pk', 'Professional grade cable ties black 200mm 100pk for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 12, 10, 285, 'Bay A-03', true),
('CCW-EL-005', 'Conduit PVC 20mm 3m Orange Heavy Duty', 'Professional grade conduit pvc 20mm 3m orange heavy duty for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 18, 14, 195, 'Bay B-19', true),
('CCW-EL-006', 'Switch Socket Double PowerPoint 10A', 'Professional grade switch socket double powerpoint 10a for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 25, 20, 165, 'Bay C-06', true),
('CCW-EL-007', 'Wire Electrical 2.5mm Twin+Earth 100m', 'Professional grade wire electrical 2.5mm twin+earth 100m for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 185, 148, 35, 'Bay D-16', true),
('CCW-EL-008', 'Junction Box Weatherproof IP66', 'Professional grade junction box weatherproof ip66 for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 32, 26, 95, 'Bay A-09', true),
('CCW-EL-009', 'Circuit Breaker MCB 20A Single Pole', 'Professional grade circuit breaker mcb 20a single pole for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 28, 22, 145, 'Bay B-05', true),
('CCW-EL-010', 'LED Bulb A60 9W E27 Cool White 10pk', 'Professional grade led bulb a60 9w e27 cool white 10pk for commercial and industrial use. High quality equipment from trusted manufacturers.', 'electrical', 55, 44, 88, 'Bay C-14', true);

-- Plumbing (10 items)
INSERT INTO products (sku, name, description, category, price, cost, stock, warehouse_location, is_active) VALUES
('CCW-PL-001', 'PVC Pipe 100mm x 3m Stormwater', 'Professional grade pvc pipe 100mm x 3m stormwater for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 28, 22, 285, 'Bay D-01', true),
('CCW-PL-002', 'Copper Pipe 15mm x 3m Type B', 'Professional grade copper pipe 15mm x 3m type b for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 45, 36, 165, 'Bay A-15', true),
('CCW-PL-003', 'Tap Basin Mixer Chrome Watermark', 'Professional grade tap basin mixer chrome watermark for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 125, 100, 42, 'Bay B-08', true),
('CCW-PL-004', 'Toilet Suite Close Coupled P-Trap', 'Professional grade toilet suite close coupled p-trap for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 385, 308, 18, 'Bay C-17', true),
('CCW-PL-005', 'Sink Laundry Tub 45L Plastic', 'Professional grade sink laundry tub 45l plastic for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 95, 76, 32, 'Bay D-12', true),
('CCW-PL-006', 'Hose Garden 18mm x 30m Fitted', 'Professional grade hose garden 18mm x 30m fitted for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 55, 44, 85, 'Bay A-02', true),
('CCW-PL-007', 'Fitting Elbow 90° 25mm PVC 10pk', 'Professional grade fitting elbow 90° 25mm pvc 10pk for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 18, 14, 195, 'Bay B-16', true),
('CCW-PL-008', 'Sealant Silicone Clear 300ml Cartridge', 'Professional grade sealant silicone clear 300ml cartridge for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 12, 10, 245, 'Bay C-03', true),
('CCW-PL-009', 'Valve Ball 25mm Brass Full Bore', 'Professional grade valve ball 25mm brass full bore for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 35, 28, 125, 'Bay D-19', true),
('CCW-PL-010', 'Tape Thread PTFE 12mm x 12m Roll', 'Professional grade tape thread ptfe 12mm x 12m roll for commercial and industrial use. High quality equipment from trusted manufacturers.', 'plumbing', 8, 6, 385, 'Bay A-06', true);
